{% set version = "0.1.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-globaloptions
  version: {{ version|replace("-", "_") }}

source:
  fn: GlobalOptions_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/GlobalOptions_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/GlobalOptions/GlobalOptions_{{ version }}.tar.gz
  sha256: 567a0a51f6b7b14127302f00e6e4944befd4964c069f96a9e61256e8c3c79ef2

build:
  number: 1001
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('GlobalOptions')"  # [not win]
    - "\"%R%\" -e \"library('GlobalOptions')\""  # [win]

about:
  home: https://github.com/jokergoo/GlobalOptions
  license: GPL (>= 2)
  summary: It provides more controls on the option values such as validation and filtering on
    the values, making options invisible or private.
  license_family: GPL3

extra:
  recipe-maintainers:
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
