{% set version = "0.1.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-globaloptions
  version: {{ version|replace("-", "_") }}

source:
  fn: GlobalOptions_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/GlobalOptions_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/GlobalOptions/GlobalOptions_{{ version }}.tar.gz
  sha256: 47890699668cfa9900a829c51f8a32e02a7a7764ad07cfac972aad66f839753e

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('GlobalOptions')"  # [not win]
    - "\"%R%\" -e \"library('GlobalOptions')\""  # [win]

about:
  home: https://github.com/jokergoo/GlobalOptions
  license: MIT
  summary: It provides more controls on the option values such as validation and filtering on the values, making options invisible or private.
  license_family: GPL3

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
