appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: o0V2Eu7q1I4hYK4HR/Z1gO3lzS98THEyR+a7J/WCrrWDuiN4Xql0XQ38gs0EWzTRppqv0OY3TIE3nAPLJI5yMr8BudVS0byObR/X/bqhQMihWzCroaw95hQaD/Fr/nLGeHNYSF5PMxvsYL0LjuBPizut6aNl0wwdhvr8ku/uvdQDD3XbI7Ua2Lyf9R59rUZnpT+w83tNKd361lo97BYWiltmwGh1qV6mmdoHxAPsBztIQOwF6o3hlL/yeTB7jQ4HBdqaAfPWTvc0xpbBqXT43en/dKNr+7NGGunw4/v4aM9JFOzzCNs4f7gVHttRdudSQ88k/Npp+dXfoJDGni7RuN4VKLd5LXjY/QOrCiI+2KraXBusIGyZKmqqlvcuVCRtAxschVS5tq739yhAiKRH96aGyARAIUKOjYHNi77kfbZLFftteqM5bCQdD9Y2JO+jlOumvie3INz4+/wkNt93XlocZ6s18wUCCkR702fLnw+hq/xsR2GUmnS7M/dYV4m/Ibf9mvLL4Vpy7SuHjNSRyDAZhBrIdwHHYjhrCOZOK4EW4yLnY7OsVN39Mx/0jpZCYU1FNwBsdy1spw1I5r7fE9fb/GMURMYP6OTN0b4njFYaeDkg1pk6NtdHxRGLNm6bvQHBPM40h4Xi+Ui2RtjimIl6PGgUA2D8b04B6zP6bts=}
