travis:
  secure:
    BINSTAR_TOKEN: D8m86agGR2cahVYBKEMWhWLUL2Ln45P75RJjDyPL9f9bGQUSpikeS0z9X48JlvXzGb026xn9KIqquBaKsTdP5mpTBGsFE45ib2d1LVwLyax1SBgmL11s/k7AYYtRKTmyq0KIG1HFZeTDMLtr5tUgxYZZQ6hYWWFUGZL1XWop34DhD7c0qPqtp1+2nU1bZ1Qu0u2iZ4VJ4TZWScpwoj2IzVmeYYGtNCHqDKYQSMROqxpi41T45nb95RD1Efa5sE4zk1y8fbq9sF0vMd+toddSPGk4vQLlZnmmJUnvGVY6Pme1Jbe29GuGNiq1etAdzrmjnA0vTiZzWmogk7PSAmjjCF+nmeJPvT7zpmaFo5HnYl5eNOzhnUhDOFvuCRbALkb0V94hNn48FWZaA4g6LF05NPAxNsC+V+ajT7OKGxM8qu7DYe2/Q+Pgxdba024/gDsbXhywwKznZUbSIsUfU3Eh8kjvJyeFK6ho3TW51fCay3nVWT87+RBAowIpvfr6F5coQfDOg8wOWHt+la/WBIMJc1OtyirJ7rj5kuM8XCNzsA676+OIq85Bh3VxHBycOHzRsBl0Xhvz4cXILLbBHt9OYtB40fLjyDf4KQEvlHALXE8HtGesO5gQxHsnaf73UCgZSYQkBcloBTHBPl6BpGxpaq5hQoIZb+OZ25wISufnIZA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
